# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QTableWidgetItem

class Ui_MainWindow(object):
    path = "config/matrix2.txt"
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(70, 21, 1181, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 350, 171, 182))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 350, 171, 299))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(480, 500, 151, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(680, 350, 171, 299))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self._3subjectName = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self._3subjectName.setObjectName("_3subjectName")
        self.verticalLayout_3.addWidget(self._3subjectName)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self._3subjectRights = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self._3subjectRights.setObjectName("_3subjectRights")
        self.verticalLayout_3.addWidget(self._3subjectRights)
        self.grantBut = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.grantBut.setObjectName("grantBut")
        self.verticalLayout_3.addWidget(self.grantBut)
        self.removeBut = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.removeBut.setObjectName("removeBut")
        self.verticalLayout_3.addWidget(self.removeBut)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(880, 350, 171, 299))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self._3_2subjectName = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self._3_2subjectName.setObjectName("_3_2subjectName")
        self.verticalLayout_4.addWidget(self._3_2subjectName)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self._3_2subjectRights = QtWidgets.QTextEdit(self.verticalLayoutWidget_4)
        self._3_2subjectRights.setObjectName("_3_2subjectRights")
        self.verticalLayout_4.addWidget(self._3_2subjectRights)
        self.createBut = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.createBut.setObjectName("createBut")
        self.verticalLayout_4.addWidget(self.createBut)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1080, 350, 171, 299))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self._3_3subjectNames = QtWidgets.QTextEdit(self.verticalLayoutWidget_5)
        self._3_3subjectNames.setObjectName("_3_3subjectNames")
        self.verticalLayout_5.addWidget(self._3_3subjectNames)
        spacerItem = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.grantAll = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.grantAll.setObjectName("grantAll")
        self.verticalLayout_5.addWidget(self.grantAll)
        self.removeAll = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.removeAll.setObjectName("removeAll")
        self.verticalLayout_5.addWidget(self.removeAll)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.grantAll.clicked.connect(self.grantAll_handler)
        self.removeAll.clicked.connect(self.removeAll_handler)
        self.removeBut.clicked.connect(self.remove_handler)
        self.grantBut.clicked.connect(self.grant_handler)
        self.createBut.clicked.connect(self.create_handler)
        self.config_table()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def create_handler(self):
        subject = self._3_2subjectName.toPlainText()
        rights = self._3_2subjectRights.toPlainText()
        self._3_2subjectRights.clear()
        self._3_2subjectName.clear()
        if subject.isnumeric():
            with open(self.path, "r+") as m:
                content = m.readline().split("|")
                users = [i.split("_")[0] for i in content if i != content[0]]
                files = content[0]
                if subject in users:
                    for r in rights:
                        if r.isalpha():
                            if r not in files:
                                content[0] = content[0] + r
                            if r not in content[users.index(subject) + 1]:
                                content[users.index(subject) + 1] = content[users.index(subject) + 1] + r
                else:
                    content.append(f"{subject}_")
                    users.append(subject)
                    for r in rights:
                        if r.isalpha():
                            if r not in files:
                                content[0] = content[0] + r
                            content[users.index(subject)+1] = content[users.index(subject)+1] + r
            print(f"create_handler: Writing {content} to file")
            with open(self.path, "w+") as m:
                content_towrite = "|".join(content)
                print(f"create_handler: Writing {content_towrite} to file")
                m.writelines(content_towrite)
                m.close()
        self.config_table()

    def grantAll_handler(self):
        subjects = self._3_3subjectNames.toPlainText()
        subjects = subjects.split(" ")
        self._3_3subjectNames.clear()
        with open(self.path, "r+") as m:
            content = m.readline().split("|")
            users = [i.split("_")[0] for i in content if i != content[0]]
            files = content[0]
            for sub_name in subjects:
                if sub_name in users:
                    content[users.index(sub_name) + 1] = sub_name + "_" + files
                else:
                    print(f"grantAll_handler: User {sub_name} doesn't exist")

        print(f"grantAll_handler: Writing {content} to file")
        with open(self.path, "w+") as m:
            content_towrite = "|".join(content)
            print(f"grantAll_handler: Writing {content_towrite} to file")
            m.writelines(content_towrite)
            m.close()
        self.config_table()

    def remove_handler(self):
        subjects = self._3subjectName.toPlainText()
        rights = self._3subjectRights.toPlainText()
        self._3subjectName.clear()
        self._3subjectRights.clear()
        subjects = subjects.split(" ")
        with open(self.path, "r+") as m:
            content = m.readline().split("|")
            files = content[0]
            users = [i.split("_")[0] for i in content if i != content[0]]
            for sub_name in subjects:
                if sub_name in users:
                    for r in rights:
                        if r in files:
                            content[users.index(sub_name) + 1] = content[users.index(sub_name) + 1].replace(r,"")
                        else:
                            print(f"remove_handler: File {r} doesn't exist")
                else:
                    print(f"remove_handler: User {sub_name} doesn't exist")

        #print(f"remove_handler: Writing {content} to file")
        with open(self.path, "w+") as m:
            content_towrite = "|".join(content)
            print(f"remove_handler: Writing {content_towrite} to file")
            m.writelines(content_towrite)
            m.close()
        self.config_table()

    def grant_handler(self):
        subjects = self._3subjectName.toPlainText()
        rights = self._3subjectRights.toPlainText()
        self._3subjectName.clear()
        self._3subjectRights.clear()
        subjects = subjects.split(" ")
        with open(self.path, "r+") as m:
            content = m.readline().split("|")
            files = content[0]
            users = [i.split("_")[0] for i in content if i != content[0]]
            for sub_name in subjects:
                if sub_name in users:
                    for r in rights:
                        if r in files and r not in content[users.index(sub_name) + 1]:
                            content[users.index(sub_name) + 1] = content[users.index(sub_name) + 1] + r
                        else:
                            print(f"grant_handler: File {r} doesn't exist or is already being owned by subject")
                else:
                    print(f"grant_handler: User {sub_name} doesn't exist")

        # print(f"remove_handler: Writing {content} to file")
        with open(self.path, "w+") as m:
            content_towrite = "|".join(content)
            print(f"grant_handler: Writing {content_towrite} to file")
            m.writelines(content_towrite)
            m.close()
        self.config_table()


    def removeAll_handler(self):
        subjects = self._3_3subjectNames.toPlainText()
        self._3_3subjectNames.clear()
        subjects = subjects.split(" ")
        with open(self.path, "r+") as m:
            content = m.readline().split("|")
            users = [i.split("_")[0] for i in content if i != content[0]]
            for sub_name in subjects:
                if sub_name in users:
                    content[users.index(sub_name) + 1] = sub_name + "_"
                else:
                    print(f"removeAll_handler: User {sub_name} doesn't exist")

        print(f"removeAll_handler: Writing {content} to file")
        with open(self.path, "w+") as m:
            content_towrite = "|".join(content)
            print(f"removeAll_handler: Writing {content_towrite} to file")
            m.writelines(content_towrite)
            m.close()
        self.config_table()


    def config_table(self):
        with open(self.path, "r+") as m:
            print("Opened file")
            content = m.readline().split("|")
            amount_files = len(content[0])
            amount_subjects = len(content) - 1
            filenames = [i for i in content[0]]
            users = [i.split("_")[0] for i in content if i != content[0]]
            self.tableWidget.setColumnCount(amount_files)
            self.tableWidget.setRowCount(amount_subjects)
            self.tableWidget.setHorizontalHeaderLabels(filenames)
            self.tableWidget.setVerticalHeaderLabels(users)
            print("Content of matrix", content)
            for row in range(self.tableWidget.rowCount()):
                for col in range(self.tableWidget.colorCount()):
                    self.tableWidget.setItem(row, col, QTableWidgetItem(""))
            for i in range(1, len(content)):
                user, user_rights = content[i].split("_")
                for sym in user_rights:
                    if sym in filenames:
                        index = filenames.index(sym)
                        self.tableWidget.setItem(users.index(user), index, QTableWidgetItem("+"))
            self.tableWidget.update()
            m.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Имена субъектов"))
        self.label_9.setText(_translate("MainWindow", "Права субъектов"))
        self.grantBut.setText(_translate("MainWindow", "Grant"))
        self.removeBut.setText(_translate("MainWindow", "Remove"))
        self.label_11.setText(_translate("MainWindow", "Имя субъекта"))
        self.label_12.setText(_translate("MainWindow", "Права субъекта"))
        self.createBut.setText(_translate("MainWindow", "Create"))
        self.label_10.setText(_translate("MainWindow", "Имена субъектов"))
        self.grantAll.setText(_translate("MainWindow", "Grant all"))
        self.removeAll.setText(_translate("MainWindow", "Remove all"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec())